package com.market.mall.dao;

import com.market.mall.bean.Cache;
import com.market.mall.bean.CacheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    long countByExample(CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int deleteByExample(CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int insert(Cache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int insertSelective(Cache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    List<Cache> selectByExample(CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    Cache selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cache record, @Param("example") CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int updateByExample(@Param("record") Cache record, @Param("example") CacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int updateByPrimaryKeySelective(Cache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    int updateByPrimaryKey(Cache record);
}