package com.market.mall.dao;

import com.market.mall.bean.Mylist;
import com.market.mall.bean.MylistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MylistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    long countByExample(MylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int deleteByExample(MylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int insert(Mylist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int insertSelective(Mylist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    List<Mylist> selectByExample(MylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    Mylist selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") Mylist record, @Param("example") MylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int updateByExample(@Param("record") Mylist record, @Param("example") MylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int updateByPrimaryKeySelective(Mylist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylist
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    int updateByPrimaryKey(Mylist record);
}