package com.market.mall.bean;

public class Cache {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cache.pid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cache.pname
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cache.amount
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cache.pprice
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private String pprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cache.pimg
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private String pimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cache.money
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cache.pid
     *
     * @return the value of cache.pid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cache.pid
     *
     * @param pid the value for cache.pid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cache.pname
     *
     * @return the value of cache.pname
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cache.pname
     *
     * @param pname the value for cache.pname
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cache.amount
     *
     * @return the value of cache.amount
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cache.amount
     *
     * @param amount the value for cache.amount
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cache.pprice
     *
     * @return the value of cache.pprice
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public String getPprice() {
        return pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cache.pprice
     *
     * @param pprice the value for cache.pprice
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setPprice(String pprice) {
        this.pprice = pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cache.pimg
     *
     * @return the value of cache.pimg
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public String getPimg() {
        return pimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cache.pimg
     *
     * @param pimg the value for cache.pimg
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setPimg(String pimg) {
        this.pimg = pimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cache.money
     *
     * @return the value of cache.money
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cache.money
     *
     * @param money the value for cache.money
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}