package com.market.mall.bean;

import java.util.Date;

public class Mylist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.oid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.uid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.pid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.begin_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.end_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.pay
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private String pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.money
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.create_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.status
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.amount
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylist.isone
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    private Integer isone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.oid
     *
     * @return the value of mylist.oid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.oid
     *
     * @param oid the value for mylist.oid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.uid
     *
     * @return the value of mylist.uid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.uid
     *
     * @param uid the value for mylist.uid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.pid
     *
     * @return the value of mylist.pid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.pid
     *
     * @param pid the value for mylist.pid
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.begin_time
     *
     * @return the value of mylist.begin_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.begin_time
     *
     * @param beginTime the value for mylist.begin_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.end_time
     *
     * @return the value of mylist.end_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.end_time
     *
     * @param endTime the value for mylist.end_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.pay
     *
     * @return the value of mylist.pay
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public String getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.pay
     *
     * @param pay the value for mylist.pay
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setPay(String pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.money
     *
     * @return the value of mylist.money
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.money
     *
     * @param money the value for mylist.money
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.create_time
     *
     * @return the value of mylist.create_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.create_time
     *
     * @param createTime the value for mylist.create_time
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.status
     *
     * @return the value of mylist.status
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.status
     *
     * @param status the value for mylist.status
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.amount
     *
     * @return the value of mylist.amount
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.amount
     *
     * @param amount the value for mylist.amount
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylist.isone
     *
     * @return the value of mylist.isone
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public Integer getIsone() {
        return isone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylist.isone
     *
     * @param isone the value for mylist.isone
     *
     * @mbg.generated Sat May 11 20:10:49 CST 2019
     */
    public void setIsone(Integer isone) {
        this.isone = isone;
    }
}