package com.market.mall.bean;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.uid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.begin_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.end_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private String pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.isone
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    private Integer isone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oid
     *
     * @return the value of order.oid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oid
     *
     * @param oid the value for order.oid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.uid
     *
     * @return the value of order.uid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.uid
     *
     * @param uid the value for order.uid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pid
     *
     * @return the value of order.pid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pid
     *
     * @param pid the value for order.pid
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.begin_time
     *
     * @return the value of order.begin_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.begin_time
     *
     * @param beginTime the value for order.begin_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.end_time
     *
     * @return the value of order.end_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.end_time
     *
     * @param endTime the value for order.end_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay
     *
     * @return the value of order.pay
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public String getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay
     *
     * @param pay the value for order.pay
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setPay(String pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.isone
     *
     * @return the value of order.isone
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public Integer getIsone() {
        return isone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.isone
     *
     * @param isone the value for order.isone
     *
     * @mbg.generated Sat May 11 16:27:28 CST 2019
     */
    public void setIsone(Integer isone) {
        this.isone = isone;
    }
}